# Generated by Django 4.0 on 2022-01-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('attendence', models.CharField(max_length=1)),
                ('roll_no', models.CharField(max_length=12)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
