# Generated by Django 4.0 on 2022-01-04 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattend',
            name='attendence',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='studentattend',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
